// api/env.js
// Vercel Serverless Function: 環境変数から Maps 設定を読み、window.__ENV__ を設定するJSを返却
module.exports = (req, res) => {
  const apiKey = process.env.GOOGLE_MAPS_API_KEY || process.env.VITE_GOOGLE_MAPS_API_KEY || '';
  const mapId = process.env.GOOGLE_MAPS_MAP_ID || process.env.VITE_GOOGLE_MAPS_MAP_ID || '';

  const js = `
// (auto-generated by Vercel /api/env)
(function() {
  window.__ENV__ = window.__ENV__ || {};
  window.__ENV__.GOOGLE_MAPS_API_KEY = ${JSON.stringify(apiKey)};
  window.__ENV__.GOOGLE_MAPS_MAP_ID = ${JSON.stringify(mapId)};
  Object.freeze && Object.freeze(window.__ENV__);
})();
`;

  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.status(200).send(js);
};
